Add code regeneration and member removal for admin
canopas/group-track-android pull request #120
Opened 2024-11-19 11:25 UTC by cp-sneh-s

# Changelog

- Implement regeneration of group invite code. (For admin)
- Implement member removal functionality for admin.

## Breaking Changes

- There was not an option to remove member from space by admin

## New Features

- SpaceInviteCodeScreen :-  Added a button to regenerate the invite new join code.
- SpaceProfileScreen :- Added a button to remove space member.

https://github.com/user-attachments/assets/22520e03-2877-4c28-a6bb-8d1de88b1e2d

https://github.com/user-attachments/assets/712cec6b-1207-4e3e-8c04-823e9f3d69d1

2024-11-20 04:00 UTC, cp-megh-l requested changes
I think most of coderabbit reviews are required to be resolved.

2024-11-22 05:02 UTC, cp-megh-l commented on data/src/main/java/com/canopas/yourspace/data/service/space/SpaceInvitationService.kt
> +    fun getInviteCodeFlow(spaceId: String): Flow<String> = callbackFlow {
There is already `getSpaceInviteCode` function, so why flow?

2024-11-22 08:04 UTC, cp-sneh-s commented on data/src/main/java/com/canopas/yourspace/data/service/space/SpaceInvitationService.kt
> +    fun getInviteCodeFlow(spaceId: String): Flow<String> = callbackFlow {
For getting real-time update for both admin and member.

2024-11-22 10:47 UTC, cp-megh-l approved these changes

2024-11-22 12:55 UTC, merged